### ISSUE TITLE
Error Integration

### ISSUE THREAD

**Issue by thierrysoler** [Minims/somfy-protect-api#10]
Hi
When I tried to integrate with :

Home Assistant 2023.4.6

Supervisor 2023.04.1

Operating System 10.1

Interface utilisateur : 20230411.1 - latest

and :

HACS Version : 1.32.1
I get the error : <Integration Minims/somfy-protect-api> Repository structure for 0.1.8 is not compliant

Thank you
Best regards

Thierry

**Comment by Minims** [comment]
This is not a hack integration for HA. use the add-on somfyProtect2 MQTT instead
