### ISSUE TITLE
Trying to recreate this in iOS Shortcuts - does the code still work in Python?

### ISSUE THREAD

**Issue by stukey** [Minims/somfy-protect-api#11]
Should this code still work? I've tried to recreate the core logic in iOS Shortcuts and am getting failures at the first step - trying to get an oauth token. Wondered if the API is still valid or maybe the client id and client secret have been revoked? Error I'm getting is: 

`{"message":"error.invalid.token","data":[],"uid":"6518040261bf6","error":"invalid_request"}`

Also trying to understand why the code base64 encodes and then decodes the client id and secret. Any help or guidance would be appreciated.

![image](https://github.com/Minims/somfy-protect-api/assets/12292623/1ff6c0cf-3512-432a-988c-2d67c22c2244)

![image](https://github.com/Minims/somfy-protect-api/assets/12292623/79f21ce9-3e9e-4389-93a9-3c9a89c5fce1)

![image](https://github.com/Minims/somfy-protect-api/assets/12292623/3a10f04e-fd4f-423f-a01b-655ad07f5383)

**Comment by Minims** [comment]
Code might still work, but I use and maintain only this one : 
https://github.com/Minims/SomfyProtect2MQTT/tree/master/somfyProtect2Mqtt/somfy_protect/api

Client_id & secret are still working.
base64 is just because in don't want to have this in plain in my repo.

Try with `curl` before trying in shortcuts, it might help. 

This is maybe easier to understand : 
https://github.com/Mystikal57/Somfy_Home_ALARM_API/blob/master/auth.php

**Comment by stukey** [comment]
Thank you. That helped me. The issue was I wasn't specifying the grant-type: password in the body of my JSON call. I guess the Python OAuth libraries do that automatically but when doing it via Shortcuts, I had to add it. Now I am getting an OAuth token! Just need to figure out how to call the actual API now! Thanks, again.

**Comment by stukey** [comment]
I'm not able to call the Somfy API, even though I am passing a valid oauth token as a header. Can you provide a couple of native example API call requests and any required headers, just to get me going? I am unable to decipher the python code because it's not making straight REST web requests, everything's obfuscated via all the python functions and libraries. I tried the other repo you linked above and mirrored what it's doing but still getting unauthorised failures.

**Comment by Minims** [comment]
The api swagger was available here bit it seems it has been removed.

**Comment by Minims** [comment]
https://api.myfox.io/api/methods#/

**Comment by stukey** [comment]
Thanks, unfortunately Somfy seems to have removed all of their developer documentation. The above URL no longer works and redirects to Somfy's French website.

**Comment by Minims** [comment]
This is working : 
```
 curl -i -H 'Content-Type: application/json' 'https://api.myfox.io/v3/site?access_token=<token>
 ```

**Comment by stukey** [comment]
Thanks again @Minims. That got me working and I can now successfully call the API to get the sites. Could you possibly provide another curl example showing setting the security level to armed.
