### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by jcorrod17** [Minims/somfy-protect-api#5]
Hello. There's a chance to integrate this into a Homebridge plugin.
Thank you in advance

**Comment by Minims** [comment]
Hello, i have not the knowledge to make it, but there is already a basic homebridge version to manage the alarm status. 
It can be enough, it depends of your usage.

On my side I'm using home assistant and the alarm is exported to Homekit with the integrated HomeAssistant component.

https://github.com/Minims/SomfyProtect2MQTT/
