### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by tomcdev63** [Minims/somfy-protect-api#8]
Hello, and thank you for this. I have a problem to get the screenshot on the website. Apparently I'm not allowed...
Any idea?

![Capture](https://user-images.githubusercontent.com/72632400/168120073-ad1b58b8-3ecb-4ce1-a963-dffc0a4eb057.JPG)

**Comment by Minims** [comment]
Hello, this is quite strange. It's like a token issue.
Can you paste me you code so I can make a try on my side  ?

**Comment by tomcdev63** [comment]
`
def get_token():
    """Retrieve a token from a file
    """
    try:
        with open(CACHE_PATH, "r") as cache:
            return json.loads(cache.read())
    except IOError:
        pass


def set_token(token) -> None:
    """WWrite a toek into a file
    """
    with open(CACHE_PATH, "w") as cache:
        cache.write(json.dumps(token))


if __name__ == "__main__":

    api = SomfyProtectApi(
        username=USERNAME, password=PASSWORD, token=get_token(), token_updater=set_token
    )

    # Check if we already have a token
    if not os.path.isfile(CACHE_PATH):
        set_token(api.request_token())

    # List Sites
    sites = api.get_sites()
    # print(sites)

    # Retieve Alarm Status
    print(f"Alarm Status for {sites[0].label} is {sites[0].security_level}")

    # Set Alarm Status
    disarmed = api.update_security_level(site_id=sites[0].id, security_level="disarmed")
    print(f"Task: {disarmed}")

    # Get Data from a Device.
    devices = api.get_devices(site_id=sites[0].id, category=Category.OUTDDOR_CAMERA)
    outdoorcamera = [OutDoorCamera(site=sites[0], device=d, api=api) for d in devices]
    for camera in outdoorcamera:
        print(
            f"Device {camera.device.label} return a Temperature of {camera.get_wifi_level_percent()} °C"
        )
        print(
            f"Device {camera.device.label} return a Link Quality of {camera.get_power_state()} %"
        )
       
    api.camera_snapshot(sites[0].id, outdoorcamera[0].get_setting("uid"))
`

**Comment by tomcdev63** [comment]
You must use Tahoma? Because I don't have it..

**Comment by Minims** [comment]
No you don't need any gateway. I don't have a Tahoma.

**Comment by Minims** [comment]
try this :
``` 
                    api.camera_refresh_snapshot(site_id=site_id, device_id=device.id)
                    response = api.camera_snapshot(site_id=site_id, device_id=device.id)
                    if response.status_code == 200:
                        # Write image to file
                        path = f"{device.id}.jpeg"
                        with open(path, "wb") as tmp_file:
                            for chunk in response:
                                tmp_file.write(chunk)
```

**Comment by tomcdev63** [comment]
![image](https://user-images.githubusercontent.com/72632400/168540560-74c7a010-e640-48d8-9611-d35b99f4c765.png)

**Comment by Minims** [comment]
Here is the full code I used to send the image via MQTT 

```
    for site_id in sites:
        try:
            for category in [
                Category.INDOOR_CAMERA,
                Category.OUTDDOR_CAMERA,
                Category.MYFOX_CAMERA,
            ]:
                my_devices = api.get_devices(site_id=site_id, category=category)
                for device in my_devices:
                    api.camera_refresh_snapshot(site_id=site_id, device_id=device.id)
                    response = api.camera_snapshot(site_id=site_id, device_id=device.id)
                    if response.status_code == 200:
                        # Write image to temp file
                        path = f"{device.id}.jpeg"
                        with open(path, "wb") as tmp_file:
                            for chunk in response:
                                tmp_file.write(chunk)
                        # Read and Push to MQTT
                        with open(path, "rb") as tmp_file:
                            image = tmp_file.read()
                        byte_arr = bytearray(image)
                        topic = f"{mqtt_config.get('topic_prefix', 'somfyProtect2mqtt')}/{site_id}/{device.id}/snapshot"
                        mqtt_publish(
                            mqtt_client=mqtt_client,
                            topic=topic,
                            payload=byte_arr,
                            retain=False,
                            is_json=False,
                        )

        except Exception as exp:
            LOGGER.warning(f"Error while refreshing snapshot: {exp}")
            continue
```
